# Generated by Django 4.2.2 on 2023-07-06 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pedidos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0010_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, validators=[pedidos.models.validar_dni], verbose_name='DNI')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero', models.CharField(editable=False, max_length=10, verbose_name='Número')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedidos.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio Unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pedidos.pedido')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productos.presentacion', verbose_name='Presentación')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
