# Generated by Django 4.2.2 on 2023-06-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.ImageField(upload_to='imagenes_producto', verbose_name='Imagen'),
        ),
    ]
